
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AHADUN ALLAHU ALSSAMADU ERROR HUWA KUFUWAN LAHU LAM QUL WALAM YAKUN YALID YOOLADUstart : V1start : V1 V2start : V1 V2 V3start : V1 V2 V3 V4V1 : QUL HUWA ALLAHU AHADUNV2 : ALLAHU ALSSAMADUV3 : LAM YALID WALAM YOOLADUV4 : WALAM YAKUN LAHU KUFUWAN AHADUN'
    
_lr_action_items = {'QUL':([0,],[3,]),'$end':([1,2,4,7,9,11,14,18,20,],[0,-1,-2,-3,-6,-4,-5,-7,-8,]),'ALLAHU':([2,6,14,],[5,10,-5,]),'HUWA':([3,],[6,]),'LAM':([4,9,],[8,-6,]),'ALSSAMADU':([5,],[9,]),'WALAM':([7,13,18,],[12,16,-7,]),'YALID':([8,],[13,]),'AHADUN':([10,19,],[14,20,]),'YAKUN':([12,],[15,]),'LAHU':([15,],[17,]),'YOOLADU':([16,],[18,]),'KUFUWAN':([17,],[19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'V1':([0,],[2,]),'V2':([2,],[4,]),'V3':([4,],[7,]),'V4':([7,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> V1','start',1,'p_start_single','syntaxic.py',4),
  ('start -> V1 V2','start',2,'p_start_two','syntaxic.py',8),
  ('start -> V1 V2 V3','start',3,'p_start_three','syntaxic.py',12),
  ('start -> V1 V2 V3 V4','start',4,'p_start_four','syntaxic.py',16),
  ('V1 -> QUL HUWA ALLAHU AHADUN','V1',4,'p_V1','syntaxic.py',20),
  ('V2 -> ALLAHU ALSSAMADU','V2',2,'p_V2','syntaxic.py',24),
  ('V3 -> LAM YALID WALAM YOOLADU','V3',4,'p_V3','syntaxic.py',28),
  ('V4 -> WALAM YAKUN LAHU KUFUWAN AHADUN','V4',5,'p_V4','syntaxic.py',32),
]
